name: Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup BuildTools
        if: steps.cache.outputs.cache-hit != 'true'
        run: mkdir BuildTools

      - name: Download BuildTools
        if: steps.cache.outputs.cache-hit != 'true'
        run: wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: 1.8.8
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.8.8

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs/*.jar
